admet_model_path: "admet_predictor_bidirec_1000epochs.pt"
activity_classifier_model_path: "Models/ActivityClassifier/checkpoints/activity_classifier_mlp.pt"
successful_molecules_path: "outputs/successful_molecules.csv"
# vae_model_path: "models/vae_model.pt"
vae_model_path: "trained_vae/vae_weights_bidirec.pt"
vocab_path: "vocab.json"